import NextAuth from 'next-auth'
import './globals.css'
import { NextAuthProvider } from '@/components/NextAuthProvider'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <NextAuthProvider>
        {children}

        </NextAuthProvider>
        </body>
    </html>
  )
}
